name: Production testing & deployment

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - "vite/**"
      - ".github/**"
  release:
    types: [published]

jobs:
  build-vite:
    # needs: build-packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: |
            vite/yarn.lock
      - name: Install Vite package
        run: cd vite && yarn
      - name: Build Vite
        run: cd vite && yarn run build
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v2
        with:
          name: vite
          path: vite/dist
          retention-days: 1

  build-app:
    needs: build-vite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "yarn"
          cache-dependency-path: "server/yarn.lock"
      - name: Download built Vite files
        uses: actions/download-artifact@v2
        with:
          name: vite
          path: server/build
      - name: Install Server package
        run: cd server && yarn
